# theme: jekyll-theme-cayman
theme: jekyll-theme-modernist
title: NEM - An Automated Program Repair Tool
description: Automated Repair of Heap-Manipulating Programs using Deductive Synthesis
github:
  is_project_page: false
